### PR TITLE
Emma sprint20

### PR DESCRIPTION
**Pull request by e-vic**
Fixed PD controller stability .... there was a misplaced minus... it stabilizes the system now. Still need to be tested further though

### CODE REVIEW

**Comment by MathiasKerman** [comment]
Sounds good, I'll review this tomorrow in the lab

**Comment by tpreynolds** [comment]
yay for stability! Sorry for flipping a minus sign, but good catch.

Can we/you check this against my pull-req so that we bring develop up to where it has both my changes and the magnetic PD controller?

**Comment by MathiasKerman** [comment]
Sure, will do. I'll have to do it tomorrow morning, though.

**Comment by e-vic** [comment]
@tpreynolds I'm pretty sure the minus sign was an error of mine, you're good ahah

**Comment by tpreynolds** [comment]
Just like Mathias' branch .. let's make pull req's when we have stable things to merge. I want to keep develop as close to "deployable" as possible real soon, so only tested code should go in. 

Just keep this branch going and re-open the pull req when we've had a chance to work out the pointing errors we saw the other day. This should be a top priority this week (let's pull in someone from DS1 maybe)

**Pull request closed without merging**
