### PR TITLE
created basic LQR loop for magnetorquer controller

### PR DESCRIPTION
**Pull request by MathiasKerman**
I just added some files, I have not changed any initialization files yet

### CODE REVIEW

**Comment by tpreynolds** [comment]
has this been tested?

**Comment by MathiasKerman** [comment]
No, Emma and I are working on a test

**Comment by scrice** [comment]
- Is the lqr magnetorquer controller in the sim? When I open the full sim, it is the version pre-descope
- Why is the linearization about 0 body rates? Could be my inexperience, is that how it is done?
- Dimensions of A matrix in linearization function is not correct.

Since I wasn't engaged with this descope plan I'm not really sure about how this pull request fits in. The dimension fix should be made then probably this should be merged so it can be tested.

**Comment by MathiasKerman** [comment]
Let me work through this Thursday. Sorry for the delay.

**Comment by tpreynolds** [comment]
You mind if I close this until we've had a chance to test the controller? Our original goal for these pull reqs was to only merge in stable stuff to develop. You can just re-open it when you have a chance to test this guy out!

**Comment by MathiasKerman** [comment]
You already did so sure :p

**Pull request closed without merging**
